GET http://localhost:3030/getUsers
Authorization: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmaXJzdE5hbWUiOiJDaHVwYSIsImxhc3ROYW1lIjoiQ2h1cHMiLCJlbWFpbCI6ImNodXBhLmNodXBhQGdtYWlsLmNvbSIsImF2YXRhciI6InBhbm5hZWZyYWdvbGEiLCJpYXQiOjE3MTIzMjYwMDIsImV4cCI6MTcxMjQxMjQwMn0.kCWXJs_CmaPy3leiZWIKBJoFpehTgz5gXRjv0y0OMVk'

####
POST http://localhost:3030/createUser
Content-Type: application/json

{
    "firstName" : "Amica",
    "lastName" : "Chips",
    "email" : "amica.chips@gmail.com",
    "password" : "12345678",
    "avatar" : "nellavitanehoprovatetante",
    "dateOfBirth" : "10-01-1958"
}

####
GET http://localhost:3030/getUsers/660da02a0b4764b2d9cb347b

####
PATCH http://localhost:3030/updateUser/660da02a0b4764b2d9cb347b
Content-Type: application/json

{
    "lastName" : "Chups"
}

####
DELETE http://localhost:3030/deleteUser/65f31cf1031ff0bd8ddde30f

####
GET http://localhost:3030/getUsers/ByName/Chu

####
GET http://localhost:3030/blogPosts

####
POST http://localhost:3030/addBlogPost
Content-Type: application/json

{
    "title": "Fourth post",
    "cover": "https://picsum.photos/200/300",
    "readTime": {
        "value": "",
        "unit": ""
    },
    "author": {
        "name": "Fourth author"
    },
    "content": "https://it.lipsum.com/"
}

####
GET http://localhost:3030/blogPosts/65f49c8e22c220ff22440c4c

####
PATCH http://localhost:3030/updateBlogPost/6602702b656eefb7a072dd23
Content-Type: application/json

{
    "author" : {
        "name": "First author"
    }
}

####
DELETE http://localhost:3030/deleteBlogPost/65f4b9942a026088f435233c


####
GET http://localhost:3030/blogPosts/ByName/second

####
GET http://localhost:3030/blogPosts?title=first&content=https

###
POST http://localhost:3030/login
Content-Type: application/json

{
    "email" : "chupa.chupa@gmail.com",
    "password" : "1234"
}